### ISSUE TITLE
Importing to 4.14.1

### ISSUE THREAD

**Issue by TheIndieDeveloper** [ChillyFlashER/Voreeal#14]
i cant import either qb or vox files it either crashes or says the file extension is not valid :( and yes its a c++ project and i moved the Voreeal folder into plugins folder of project, i downloaded it using SorceTree, and the plugin launched and i can see Voreeal stuff in the blueprint but there is only 2 things :P

**Comment by erictuvesson** [comment]
Hey, last time I tried importing voxel files it worked fine. Just there were some rendering queue issues where the mesh sometimes wont update, probably has something to do with my latest commits. 

*This project is not fully complete and not really ready to be used.*

**Comment by VoxelBuddy** [comment]
When do you think the plugin will be functional again?

**Comment by VoxelBuddy** [comment]
?

**Comment by johnfg2610** [comment]
this might take a while as its quite complex but im sure chilly is working very hard to get it fixed and working correctly you will have to be patient

**Comment by erictuvesson** [comment]
I am working on the project when I have time, but I currently have no reason to use this project therefor it's not a project I am prioritizing.

**Comment by erictuvesson** [comment]
It does work to some extent now. The import system supports MagicaVoxel(.vox) and Qubicle Binary(.qb), it doesn't support Voxlap(.vox). I haven't found any file structure for Voxlap so I can't add support for it.

**Comment by VoxelBuddy** [comment]
Failed to import '../../../../../../Users/Tomas/Desktop/MagicaVoxel-0.98/vox/Melee Weapons/wep_big_war_hammer.vox'. Failed to create asset '/Game/Assets/VoxelModels/wep_big_war_hammer'.
Please see Output Log for details.

**Comment by VoxelBuddy** [comment]
qb format seam to be working fine :) 
but the actual model does not showup :3

**Comment by erictuvesson** [comment]
@VoxelBuddy If the vox file outputted "Volume has no size." in the Output Log it most likely means it's a Voxlap file, not a MagicaVoxel file. 
The editor viewer doesn't display the volume for some unexpected reason. However if you drag it into the level it should display just fine, just that it might be a bit small.

**Comment by VoxelBuddy** [comment]
well i have tried all formats from magica voxel exported and nothing works :3 am i missing something? they wont render, i cant see anything want me to make a video for you?

**Comment by VoxelBuddy** [comment]
it looks like magicavoxel only exports in Voxlap file when saving as .vox, and only format that works to a small part is qb as it does not render, so how do i export to .vox without it being Voxlap?

**Comment by erictuvesson** [comment]
I successfully imported all vox files from [mmmm](https://github.com/mikelovesrobots/mmmm) and they worked fine, just that sometimes the material turns black. I have even made a my own model in MagicaVoxel and exported it as vox.

**Comment by VoxelBuddy** [comment]
when i import .slab.vox format it says 
"Magic number does not match. (28 != 542658390) 
Error: Cannot load file header."

**Comment by VoxelBuddy** [comment]
have i done something wrong then?

**Comment by VoxelBuddy** [comment]
ill make a small video for you so you can see

**Comment by VoxelBuddy** [comment]
here you go https://www.youtube.com/watch?v=oafosKJXdXg

**Comment by ChillyFlashER** [comment]
Add me on Skype 'eric.tuvesson'

**Comment by VoxelBuddy** [comment]
added you :)

**Comment by erictuvesson** [comment]
I am closing this issue because I will most likely never work more on this project since I don't have the time and there are better alternatives out there now.
